# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/NewDownloadDialog.ui'
#
# Created: Mon Oct 21 15:52:07 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_NewDownloadDialog(object):
    def setupUi(self, NewDownloadDialog):
        NewDownloadDialog.setObjectName("NewDownloadDialog")
        NewDownloadDialog.resize(318, 322)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/project-development-new-template.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewDownloadDialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(NewDownloadDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(NewDownloadDialog)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.edtUrl = QtGui.QLineEdit(NewDownloadDialog)
        self.edtUrl.setObjectName("edtUrl")
        self.verticalLayout_3.addWidget(self.edtUrl)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.line = QtGui.QFrame(NewDownloadDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtGui.QLabel(NewDownloadDialog)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtGui.QLabel(NewDownloadDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edtDir = QtGui.QLineEdit(NewDownloadDialog)
        self.edtDir.setObjectName("edtDir")
        self.horizontalLayout_2.addWidget(self.edtDir)
        self.btnDir = QtGui.QToolButton(NewDownloadDialog)
        self.btnDir.setObjectName("btnDir")
        self.horizontalLayout_2.addWidget(self.btnDir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(NewDownloadDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.spinSpeed = QtGui.QSpinBox(NewDownloadDialog)
        self.spinSpeed.setMaximum(9999)
        self.spinSpeed.setProperty("value", 10)
        self.spinSpeed.setObjectName("spinSpeed")
        self.horizontalLayout.addWidget(self.spinSpeed)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(NewDownloadDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.spinConnections = QtGui.QSpinBox(NewDownloadDialog)
        self.spinConnections.setProperty("value", 5)
        self.spinConnections.setObjectName("spinConnections")
        self.horizontalLayout_3.addWidget(self.spinConnections)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btnOk = QtGui.QPushButton(NewDownloadDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/dialog-ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon1)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_4.addWidget(self.btnOk)
        self.btnCancel = QtGui.QPushButton(NewDownloadDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/dialog-cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon2)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(NewDownloadDialog)
        QtCore.QMetaObject.connectSlotsByName(NewDownloadDialog)

    def retranslateUi(self, NewDownloadDialog):
        NewDownloadDialog.setWindowTitle(QtGui.QApplication.translate("NewDownloadDialog", "Add URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NewDownloadDialog", "Add New URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewDownloadDialog", "Download options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewDownloadDialog", "Download Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDir.setText(QtGui.QApplication.translate("NewDownloadDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NewDownloadDialog", "Maximum Download Speed (kb/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NewDownloadDialog", "Number of Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("NewDownloadDialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("NewDownloadDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
